5.1.var Versus let: Hoisting!
There's one other reason to use let instead of var. To understand it, we need to get really nerdy and talk about something with a cool name: variable ahoy-sting. I mean, variable hoisting.

At the top of the play file, do something terrible: console.log(bar)
I know! This doesn't even make sense - there is no variable called bar! When we try it, we get:

  ReferenceError: bar is not defined